#!/bin/bash

# this is a file checkout – do nothing
if [ "$3" == "0" ]; then exit; fi

newBranchName=$(git symbolic-ref --short -q HEAD)
numberOfCheckouts=`git reflog --date=local | grep -o ${newBranchName} | wc -l`

for branch in $(git branch --color=never --contains $1 | sed -e 's/^..//');
do
  if [ "$(git show-ref -s $branch )" == $1 ] && [ "$branch" != "$newBranchName" ]; then
    parentBranchName=$branch;
  fi
done

#if the refs of the previous and new heads are the same
#and the number of checkouts equals one, a new branch has been created
if [ "$1" == "$2"  ] && [ ${numberOfCheckouts} -eq 1 ]; then
    git commit --allow-empty -m "Branching from $parentBranchName to $newBranchName"
fi